/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

const getNumDivisors = num => {
  const sqrt = Math.floor(Math.sqrt(num))
  let numDiv = 0

  for (let i = sqrt; i > 0; i--) {
    // every dividend > sqrt can be multiplied by one above sqrt for the product
    if (num % i === 0) numDiv += 2
  }

  return numDiv
}

const findTriangle = numDiv => {
  let sum = 0
  let i = 0
  let found = false

  while (!found) {
    sum += i
    i++

    if (getNumDivisors(sum) >= numDiv) {
      found = true
    }
  }

  return sum
}

// ✔ Solved: 76576500
console.log(findTriangle(5e2))
