/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms
 */

function fibEven (num1, num2, sum) {
  if (num2 >= 4000000) {
    return sum
  }

  const nextNum = num1 + num2

  if (num2 % 2 === 0) {
    return fibEven(num2, nextNum, (sum + num2))
  }

  return fibEven(num2, nextNum, sum)
}

// Solved, prints 4613732
console.log(fibEven(1, 2, 0))
